# Generated by Django 5.0 on 2024-08-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
