# Generated by Django 5.0 on 2024-08-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Actor_Actress', 'Actor_Actress'), ('Director', 'Director'), ('Producer', 'Producer')], max_length=15)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
